### PR TITLE
- Added LICENSE file.

### PR DESCRIPTION
**Pull request by manwar**
Hi Jeffrey, please review the above change.

Many Thanks.
Best Regards,
Mohammad S Anwar

### CODE REVIEW

**Comment by jeffa** [comment]
I already have a License ... why do you feel this pull is necessary?

**Comment by manwar** [comment]
I still don't see it. I must be missing something here. It's not listed on MetaCPAN.

**Comment by jeffa** [comment]
If anyone is missing something it is me. :) The license is at the bottom of the .pm ... do you think it is better to have a separate file instead for the license?

**Comment by manwar** [comment]
It is recommended to have LICENSE file in the distribution as well as documented in the pod according to CPANTS.

**Pull request closed without merging**
